### ISSUE TITLE
Problem with Reolink RLC-520A

### ISSUE THREAD

**Issue by samsix** [berfenger/cam2mqtt#10]
Hi,

I set up the software for two Reolink RLC-810A und everything is working absolutly fine.
Today I added an Reolink RLC-520A ( v3.1.0.801_22010701) with the same setting like on my 810A.
But I didn´t receive any AI events via MQTT.

Here is my config:
`mqtt:
  host: 192.168.XXX.XXX
  port: 1888
  username: username
  password: password
  #base_name: cam2mqtt
  ssl: false
  #required: true # leave it on true (default) to avoid losing messages on startup

webhook:
  external_url: http://192.168.XXX.XXX:8081 # only needed for webhook subscriptions

cameras:
  Hof:
    host: 192.168.XXX.XXX
    username: username
    password: password
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        port: 443 # optional. 443/HTTPS by default
        # username: username # optional. Alternative username for Reolink API
        # password: password # optional. Alternative password for Reolink API
        ssl: true # optional. Use ssl/HTTPS
        sync_datetime: false

  Terrasse:
    host: 192.168.XXX.XXX
    username: username
    password: password
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        port: 443 # optional. 443/HTTPS by default
        # username: username # optional. Alternative username for Reolink API
        # password: password # optional. Alternative password for Reolink API
        ssl: true # optional. Use ssl/HTTPS
        sync_datetime: false

  Haustur:
    host: 192.168.XXX.XXX
    username: username
    password: password
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        port: 443 # optional. 443/HTTPS by default
        # username: username # optional. Alternative username for Reolink API
        # password: password # optional. Alternative password for Reolink API
        ssl: true # optional. Use ssl/HTTPS
        sync_datetime: false
`

I already compared all settings on the cameras, but they are all the same. 
Does anyone else have Problem wit the RLC-520A ?

**Comment by berfenger** [comment]
Hi @samsix,

I also have the RLC-520A, and there are some issues with old firmware versions.
There are 2 hardware versions for the RLC-520A: IPC_523128M5MP and IPC_523128M5MP_V2.
If you have an `IPC_523128M5MP`, you can download the latest firmware (`v3.1.0.951_22041566`) from the [Reolink Download Center](https://reolink.com/download-center/). On this firmware, the camera should report AI object detection events through ONVIF and it should work OK with cam2mqtt.
If you have the newer hardware version (`IPC_523128M5MP_V2`), you will have to wait for Reolink to publish the new firmware that implements the new ONVIF protocol.
There is a workaround that may help on an older firmware. Just turn the motion detection slider all the way up (Settings > Camera > Detection Alarm > Sensitivity > Motion Detection), and the camera should report AI detection states only while motion is detected.

**Comment by samsix** [comment]
Hi,

I have the IPC_523128M5MP_V2 Version and you are right, when I turn on the Motion detection everthing works fine.

It's pretty odd that tuning on the motion detection to use the smart detection only seems to affect the ftp upload and the onvif status. The videos on the SD Card are working even with the motion detection set to 1.

But that is a problem for Reolink.

Thank you very much for this awesome little software and your Support.
