### ISSUE TITLE
Alerts of objects outside the detection zone?

### ISSUE THREAD

**Issue by curana** [berfenger/cam2mqtt#18]
Hi,

I get alerts for objects which are outside of the detection zone of my camera.
Is this an issue of cam2mqtt (maybe a known limitation) or maybe an issue with the Reolink-API being used?

Thanks.

**Comment by berfenger** [comment]
Hi,

cam2mqtt only sends events that the camera reports through ONVIF. So maybe there is a problem on the camera firmware or camera config.
Please note that the area that you draw (blue or grey) is the area where you *don't* want motion to be detected. It is quite confusing on older firmwares.

**Comment by curana** [comment]
Thanks, maybe it's an issue with the firmware then.

Like you described, all the areas that should NOT trigger an event are grey. But still I get some.
It does seem to help though if I add the minimum size of an object.
